---

image: "reporunner/archlinux"
checkout_dir: /go/src/github.com/Luzifer/go-latestver

commands:
  # Dependencies for downloading libraries
  - echo -e "[luzifer]\nSigLevel = Optional TrustAll\nServer = https://s3-eu-west-1.amazonaws.com/arch-luzifer-io/repo/\$arch" >>/etc/pacman.conf
  - pacman -Syy --noconfirm base-devel git go golangci-lint-bin sqlite3
  - make go_test

environment:
  CGO_ENABLED: 1
  GOPATH: /go
