apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-latestver.fullname" . }}
  labels:
    {{- include "go-latestver.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
