name: test-and-build

on:
  push: {}

permissions:
  contents: write
  issues: write

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:ee15c1d016b1b4eaefb9ce1403ad8f272489f48b1a47d36922a30d5052600a8b
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: forgejo

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 'Lint and test code'
        run: make go_test helm_lint

      - name: Do a quick local compile
        run: make build
